//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Operation_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        public int id { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
        public string First_Name { get; set; }
        public string last_Name { get; set; }
        public string Date_of_Birth { get; set; }
        public string Gender { get; set; }
    
        public virtual TeacherMaster TeacherMaster { get; set; }
    }
}
